name = "coinecta/staking-contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'coinecta/staking-contracts'"

[repository]
user = "coinecta"
project = "staking-contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "main"
source = "github"
